### ISSUE TITLE
Publish BingChat.Cli as tool to nuget

### ISSUE THREAD

**Issue by neon-sunset** [bsdayo/BingChat#19]
Publishing `BingChat.Cli` as tool would allow for `dotnet tool install -g BingChat.Cli` without having to build it and add to $PATH manually.

(also, version 0.8.0 when?😅)

**Comment by bsdayo** [comment]
Sorry for the late reply, I am preparing for a very important entrance examination these days and have not had much time to devote to this project.

v0.8.0 has been released.

The `BingChat.Cli` project has also been renamed to `dotnet-bingchat` and is available on nuget. I'll update the README later.

```
dotnet tool install -g --prerelease dotnet-bingchat
```

Also, the live display for CLI is also implemented. Hopefully it will get a better UX.
