### ISSUE TITLE
Timout until chat session expires?

### ISSUE THREAD

**Issue by hswlab** [bsdayo/BingChat#31]
Hi, in the roadmap description it says that it is possible to set a timeout. Unfortunately I didn't find any option in this context in the current version of the library. Is this implementation not checked in yet? I would be interested in how long you have until the chat session expires if you don't make a request and is it possible to configure this timeout?

**Comment by neon-sunset** [comment]
Bing Chat conversations have no expiration beyond what is offered by its retention policy (basically, how long your chats are being kept in your chat history).

The timeout in the roadmap refers to being able to timeout the requests that are being sent to Bing Chat API with `CancellationToken`. E.g.:
```cs
using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(15));
var client = new BingChatClient(new()
{
    CookieU = "your-cookie_u-token",
    Tone = BingChatTone.Balanced,
});

Console.WriteLine("Please wait...");
  
var message = "Do you like cats?";
var answer = await client.AskAsync(message, cts.Token);

Console.WriteLine($"Answer: {answer}");
```

**Comment by hswlab** [comment]
Ok, thanks for your help :)
