### ISSUE TITLE
I'm getting a BingChatException: 'Success'

### ISSUE THREAD

**Issue by peavey2787** [bsdayo/BingChat#6]
I have added BingChat to my project and copied my bing.com's "_U" cookie value, but when I try to run var answer = await client.AskAsync("Whats the weather like?"); I get this error: BingChat.BingChatException: 'Success: .'

How would I go about fixing this?

**Comment by bsdayo** [comment]
Looks like a duplicate of #5. The latest version (v0.4.1) may have fixed this problem, you can try it.
