### ISSUE TITLE
UnauthorizedRequest Exception

### ISSUE THREAD

**Issue by Caulm** [bsdayo/BingChat#8]
Message
```
UnauthorizedRequest: Sorry, you need to login first to access this service.. If you confirm that the correct cookie is set and you still keep seeing this, maybe Bing doesn't serve your region. You can use a proxy and try again.
```
I have added "bing.com" to my VPN pac list, and I can access Bing AI in Edge browser.
I have set the cookie and proxy in code like tihs. The exception still exist.
```
HttpClient.DefaultProxy = new WebProxy("127.0.0.1:8807"); //local proxy
var client = new BingChatClient(new BingChatClientOptions
{
    Cookie = File.ReadAllText(cookiePath),
});
var conversation = await client.CreateConversation();
```

**Comment by Caulm** [comment]
I tried to set all cookie values and the request succeed.
Seems that more cookie values are needed, besides the "_U" vaule.

**Comment by Caulm** [comment]
是的，我试了两种方法获取`_U`的值
（1）在Edge上安装Cookie Editor，从里面复制_U的值
（2）F12->应用程序->Cookie，从里面复制
得到结果是一样的，是一个由字母、下划线、横杠组成的字符串。
然后我把复制内容存在txt文件中，txt文件路径存在变量`cookiePath`中，程序运行时读取。

另外，用Postman发送请求也是一样现象。只包含`_U`的值的话，会返回UnauthorizedRequest。包含全部cookie能请求成功。
![image](https://user-images.githubusercontent.com/40651411/236104626-997148b6-4172-4ea5-98f0-8d1a34b7a586.png)
![image](https://user-images.githubusercontent.com/40651411/236104563-871e3a13-e789-4b31-a7f7-66422a56efec.png)

**Comment by bsdayo** [comment]
仍然没有复现成功
能测试出具体少了哪项 cookie 会导致失败吗？发现了也可以直接提个 PR
